only my action

diff --git a/.github/workflows/notify.yml b/.github/workflows/notify.yml
--- a/.github/workflows/notify.yml
+++ b/.github/workflows/notify.yml
@@ -2,20 +2,18 @@ name: Blinkist Notify
 
 on:
   workflow_dispatch:
-  push:
-    branches: [ main ]
 
 jobs:
   run-and-notify:
     runs-on: ubuntu-latest
     steps:
-      #- name: Run container
-      #  id: run
-      #  continue-on-error: true
-        # run: |
-        #   set -o pipefail
-        #   docker run --rm -v "$GITHUB_WORKSPACE/downloads":/downloads ghcr.io/nicoweio/blinkist:latest --freedaily /downloads || echo "FAILED" > /tmp/run_status || true
-        #   if [ -f /tmp/run_status ]; then echo "status=failed" >> $GITHUB_OUTPUT; else echo "status=success" >> $GITHUB_OUTPUT; fi
+      - name: Run container
+        id: run
+        continue-on-error: true
+        run: |
+          set -o pipefail
+          docker run --rm -v "$GITHUB_WORKSPACE/downloads":/downloads ghcr.io/nicoweio/blinkist:latest --freedaily /downloads || echo "FAILED" > /tmp/run_status || true
+          if [ -f /tmp/run_status ]; then echo "status=failed" >> $GITHUB_OUTPUT; else echo "status=success" >> $GITHUB_OUTPUT; fi
 
       - name: send default message
         uses: appleboy/telegram-action@master
